# Signature weapons (live wiki "Signature Weapon" page, 2026-10-05): weapon -> (frame, bonus)
SIG = {
 'Tekko Prime':('Atlas Prime','+6% Status Chance'),
 'Euphona Prime':('Banshee Prime','Signature, bonus not implemented'),
 'Cobra & Crane Prime':('Baruuk Prime','First combo strike sleeps 2s (not allocated: Desert Wind replaces Melee)'),
 'Venato Prime':('Caliban Prime','+50% Melee Combo Counter Chance'),
 'Vadarya Prime':('Caliban Prime','Signature, bonus not implemented'),
 'Steflos Prime':('Citrine Prime','+40% Projectile Speed'),
 'Corufell Prime':('Citrine Prime','+20% Heavy Attack Wind Up Speed'),
 'Reconifex':('Cyte-09','Signature, bonus not implemented (not allocated: Neutralizer replaces Primary)'),
 'Dorrclave':('Dagath','Heals 6 HP per active status on strike'),
 'Ruvox':('Dante','Signature, bonus not implemented'),
 'Skiajati':('Excalibur Umbra','Signature, bonus not implemented (not allocated: Exalted Blade replaces Melee)'),
 'Enkaus':('Follie','Alt-fire applies Inkblot passive'),
 'Astilla Prime':('Gara Prime','+80 Ammo Max'),
 'Fusilai':('Gara Prime','+50% Projectile Speed'),
 'Volnus Prime':('Gara Prime','+100% radial Slam damage'),
 'Nagantaka Prime':('Garuda Prime','+1m Punch Through'),
 'Acceltra Prime':('Gauss Prime','Sprint reload buff +50%'),
 'Akarius Prime':('Gauss Prime','Sprint reload buff +100%'),
 'Masseter Prime':('Grendel Prime','CC immunity during Heavy Attacks'),
 'Alternox Prime':('Gyre Prime','+20% Multishot'),
 'Knell Prime':('Harrow Prime','+1 Magazine'),
 'Scourge Prime':('Harrow Prime','Signature, bonus not implemented'),
 'Larkspur Prime':('Hildryn Prime','+300 Ammo Max in atmosphere (ARCHGUN - not a Primary)'),
 'Evensong':('Jade','Signature, bonus not implemented'),
 'Cantare':('Jade','Signature, bonus not implemented'),
 'Harmony':('Jade','Signature, bonus not implemented'),
 'Hystrix Prime':('Khora Prime','8% instant reload on headshot'),
 'Dual Keres Prime':('Khora Prime','20% Heavy Attack Efficiency'),
 'Higasa':('Koumei','Signature, bonus not implemented'),
 'Amanata':('Koumei','Signature, bonus not implemented'),
 'Rauta':('Kullervo','+7s Melee Combo duration'),
 'Cedo Prime':('Lavos Prime','Shotgun Ammo Mutation effect'),
 'Akzani':('Mirage Prime','Signature, bonus not implemented (not allocated)'),
 'Nunchasa':('Narin','Signature, bonus not implemented'),
 'Aksondol':('Narin','Signature, bonus not implemented'),
 'Arbucep':('Nokko','Shooting Stinkbrain/Brightbonnet triggers pulses (ARCHGUN)'),
 'Pandero Prime':('Octavia Prime','Alt-fire headshot kills +20% reload'),
 'Tenora Prime':('Octavia Prime','Alt-fire headshot kills 20% mag refill'),
 'Scyotid':('Oraxia','Signature, bonus not implemented'),
 'Spinnerex':('Oraxia','Signature, bonus not implemented'),
 'Wrath':('Sirius & Orion','Signature (Orion), bonus not implemented (not allocated)'),
 'Pride':('Sirius & Orion','Signature (Sirius), bonus not implemented (not allocated)'),
 'Velox Prime':('Protea Prime','Ammo Efficiency 40%'),
 'Mandonel':('Qorvex','Charged beams empower Chyrinka Pillar (ARCHGUN)'),
 'Phantasma Prime':('Revenant Prime','+4 Magazine'),
 'Tatsu Prime':('Revenant Prime','+4 Soul Swarm charges'),
 'Epitaph Prime':('Sevagoth Prime','+20% headshot damage'),
 'Afentis Prime':('Styanax Prime','+4 flat Ammo Max'),
 'Riot-848':('Temple','Signature, bonus not implemented (not allocated)'),
 'Perigale Prime':('Voruna Prime','+24 Ammo Max'),
 'Sarofang Prime':('Voruna Prime','Heavy Slam vortex at 5x combo'),
 'Vinquibus':('Uriel','Signature, bonus not implemented; occupies Primary AND Melee'),
 'Fulmin Prime':('Wisp Prime','Faster auto/semi mode switch'),
 'Quassus Prime':('Xaku Prime','Heavy Attack daggers +Accuracy'),
 'Kompressa Prime':('Yareli Prime','+30% Projectile Speed'),
}
ELEMENT = {'Kuva Hek':'toxin','Tenet Plinx':'toxin','Tenet Diplos':'toxin','Tenet Detron':'radiation','Kuva Nukor':'heat',
 'Kuva Sobek':'toxin','Tenet Arca Plasmor':'radiation','Kuva Bramma':'heat','Tenet Cycron':'toxin','Kuva Ogris':'toxin',
 'Kuva Twin Stubbas':'heat','Tenet Spirex':'electricity'}
# Rationale for changed / newly assigned slots
CHANGES = {
 ('Baruuk Prime','Primary'):('OPEN','Paris Prime','Afentis is Styanax signature. Paris Prime Incarnon: high-end bow, unallocated, Genesis farmable. Tier D/E.'),
 ('Dante','Primary'):('Ruvox','Phenmor','Ruvox is a MELEE (Fist), not a Primary. Phenmor: Entrati/Albrecht innate Incarnon rifle, Whispers-era fit (D).'),
 ('Dante','Melee'):('Ekhein','Ruvox','Ruvox is Dante signature melee (A/B claim, innate Incarnon). Ekhein released to pool.'),
 ('Garuda Prime','Secondary'):('Zakti Prime','Despair','Zakti Prime duplicate (Garuda vs Nezha); neither has a signature claim. Nezha keeps it (Prime Access tie-break only). Despair Incarnon: thrown blades suit talon kit (D).'),
 ('Hildryn Prime','Primary'):('Larkspur Prime','Gorgon Wraith','Larkspur Prime is an ARCHGUN, so the Primary slot was effectively empty. Larkspur moved to an Archgun signature extra. Gorgon Wraith Incarnon (E).'),
 ('Koumei','Secondary'):('Kompressa','Kunai','Kompressa line is Yareli signature (+30% Projectile Speed); Kompressa Prime exists. Kunai Incarnon: Japanese-themed thrown sidearm (D).'),
 ('Narin','Melee'):('OPEN','Prisma Skana','Nurinarim is a cast sword-dance ability (scales on Ability Strength, 20s, no weapon mods), not a wielded weapon, so it does NOT replace Melee. Prisma Skana Incarnon: sword fits Iceblade theme (D).'),
 ('Nokko','Primary'):('OPEN','Sporothrix','Fungal sniper rifle, direct Nokko (mushroom) thematic fit (D). Signature Arbucep is an Archgun.'),
 ('Nokko','Secondary'):('OPEN','Ocucor','Released from Yareli; Deimos/Infested-growth thematic fit (D).'),
 ('Nokko','Melee'):('OPEN','Mios','Released from Uriel (Vinquibus covers Melee); Infested blade-whip fit (D).'),
 ('Oraxia','Primary'):('OPEN','Torid','Toxin launcher Incarnon; venom/spider fit (D).'),
 ('Qorvex','Secondary'):('Laetum','Bronco Prime','Laetum duplicate (Qorvex vs Xaku). Xaku keeps it (Void/Zariman fit). Bronco Prime Incarnon: hitscan sidearm exploits +3 Punch Through passive (C).'),
 ('Qorvex','Melee'):('Quassus','Hate','Quassus is XAKU signature; Qorvex had no claim. Hate Incarnon (E).'),
 ('Styanax Prime','Primary'):('Afentis','Afentis Prime','Afentis Prime is live; same signature bonus line.'),
 ('Uriel','Melee'):('Mios','Vinquibus (Melee)','Vinquibus occupies BOTH Primary and Melee slots, so Mios was impossible to equip alongside it.'),
 ('Wukong Prime','Secondary'):('Pyrana Prime','Ballistica Prime','Pyrana Prime duplicate (Limbo vs Wukong). Limbo keeps it (Prime Access tie-break only). Ballistica Prime Incarnon (E).'),
 ('Yareli Prime','Secondary'):('Ocucor','Kompressa Prime','Signature with a mechanical bonus (+30% Projectile Speed), tier A.'),
}
CHANGES.update({
 ('Temple','Secondary'):('Athodai','Riot-848','v4.1 reconciliation: Riot-848 is Temple\'s signature machine pistol (Update 38.5). The slot is uncontested and Athodai has no Temple claim. Signature bonus is not implemented, so this is a tier D signature preference.'),
 ('Mirage Prime','Secondary'):('Prisma Twin Gremlins','Akzani','v4.1 reconciliation: Akzani is Mirage\'s signature dual pistol; the slot is uncontested (tier D signature preference).'),
 ('Sirius & Orion','Melee'):('Caustacyst','Pride','v4.1 reconciliation: Pride (Sirius) / Wrath (Orion) are the twins\' signature heavy scythes (Update 43). The twins share one weapon loadout, so one Melee slot. Pride is Sirius, the default Primary Son. Wrath is listed as an optional extra.'),
})
CORRECTIONS = [
 ('Roster','Roster may contain new frames/Primes','Live wiki data 2026-10-05: no new released frames or Primes since the 66-frame snapshot. Brysko is announced for the Tau update (Late 2026/Early 2027). Excalibur Umbra Prime is China-build only.','Roster unchanged at 66 frames. Brysko goes on a watchlist.','Frame counts unchanged.'),
 ('Uriel','Vinquibus Primary + Mios Melee','Vinquibus wiki: "Equipping Vinquibus will occupy both primary and melee weapon slots."','Uriel Melee = Vinquibus (Melee). Mios released.','One fewer weapon, slot and catalyst. Mios reassigned to Nokko.'),
 ('Dante','Ruvox as Primary','Weapon data: Ruvox is a Melee Fist and Dante\'s signature melee. Ekhein is also Melee.','Phenmor / Onos / Ruvox. Ekhein dropped.','Dante had no valid Primary and two Melees.'),
 ('Hildryn','Larkspur Prime as Primary','Weapon data: Larkspur Prime Slot = Archgun.','Gorgon Wraith takes Primary. Larkspur Prime becomes an Archgun signature extra (Archweapon slot).','Adds one Primary weapon and one Genesis adapter.'),
 ('Rhino','Ankyros Prime Incarnon','Incarnon page and weapon data: no Ankyros Incarnon exists.','Ankyros Prime kept as an ordinary weapon. Incarnon flag removed.','Removes one Genesis requirement.'),
 ('Vauban','Kulstar Incarnon','Incarnon page and weapon data: no Kulstar Incarnon exists.','Kulstar kept as an ordinary weapon. Incarnon flag removed.','Removes one Genesis requirement.'),
 ('Incarnon list','20-item historical Incarnon list','Allocated weapons with a live Incarnon now total 39: 32 need a Genesis adapter and 7 are innate (Innodem, Praedos, Ruvox, Phenmor, Onos, Felarx, Laetum). Sybaris Prime, Sicarus Prime and Okina Prime were already allocated but were not flagged.','Incarnon list rebuilt from live data.','Genesis adapters are farmable (Steel Path Circuit), not plat.'),
 ('Styanax','Afentis','Afentis Prime is live (Update 43) with the same signature bonus.','Afentis Prime.','Afentis Prime Set priced instead of base Afentis.'),
 ('Yareli / Koumei','Koumei holds Kompressa, Yareli uses Ocucor','Kompressa / Kompressa Prime are Yareli signatures (+30% Projectile Speed). Koumei has no claim.','Yareli: Kompressa Prime. Koumei: Kunai. Ocucor goes to Nokko.','Kompressa Prime Set priced.'),
 ('Qorvex','Felarx / Laetum / Quassus','Quassus is Xaku\'s signature line. Laetum collides with Xaku. Qorvex\'s only signature is the Mandonel archgun. The passive is +3 Punch Through for any weapon.','Felarx / Bronco Prime / Hate, plus Mandonel.','Removes two collisions.'),
 ('Narin','Nurinarim LIVE TEST','Ability page: a 20s sword-dance ability that drains Ice and scales on Ability Strength, with no weapon modding. Same doctrine class as the U38.5 cast-based conversions.','No replacement. Ordinary Melee required: Prisma Skana.','Adds one Melee.'),
 ('Dante','Noctua not addressed','Weapon data: Noctua is an Exalted secondary (first ability).','Treated like Jade\'s Glory: an additional Exalted that does not replace Onos.','LIVE TEST if a different ruling is wanted.'),
 ('Garuda','Garuda Talons as Exalted','Weapon data: Garuda Prime Talons is class Claws, used when no melee is equipped (passive). No slot or catalyst.','Kept as practical Melee. Excluded from slot and catalyst counts.','-'),
 ('Protea','Roar replaces Temporal Anchor while running Temporal Artillery','Mod data: Temporal Artillery is a Blaze Artillery augment that only triggers "When Temporal Anchor is activated".','INTERNALLY INVALID. Recommended: Roar over Grenade Fan, keeping Temporal Anchor + Temporal Artillery. Alternative: keep Roar on Anchor and drop Temporal Artillery.','Build sheet must be edited in the v3 workbook (not available here).'),
 ('Mesa','Regulators credited as Melee','Weapon data lists Regulators Prime as an Exalted Secondary.','Project doctrine kept (Melee credit). Game-side slot noted.','None.'),
 ('Duplicates','"Zero duplicates" after earlier cleanup','Logical audit of 66x3 slots found exact duplicates Zakti Prime, Pyrana Prime and Laetum, plus a hidden Quassus/Quassus Prime signature conflict.','All resolved (see Weapon Allocation). 0 exact duplicates.','Variant-family pairs remain by design: Vectis/Vectis Prime, Trumna/Trumna Prime, Dual Keres/Prime, Epitaph/Prime, Cedo/Prime, Pyrana/Pyrana Prime, Ohma/Prisma Ohma.'),
 ('Zephyr','Catchmoon','Catchmoon is a Kitgun chamber and not tradeable.','Kept. Classified as farmable (Solaris United).','No plat.'),
 ('Temple / Mirage / S&O','Signature weapons left unallocated (Riot-848, Akzani, Pride/Wrath)','Live equipment reconciliation: each is the frame\'s own signature weapon for an uncontested, non-Exalted slot.','v4.1: Temple Riot-848, Mirage Akzani, S&O Pride (+ Wrath optional). Athodai, Prisma Twin Gremlins and Caustacyst released.','Weapon count unchanged; Akzani, Pride and Riot-848 procurement routes differ.'),
 ('v4.3 B3 SYSTEMIC: weapon templates','Every Primary/Secondary received a crit template (Point Strike / Pistol Gambit...) regardless of base crit','Weapon data: Pox 1%, Zymos 5%, Rauta 6%, Akbronco 6%, Mara Detron 8%, Cyanex 8%... base crit. Relative crit mods multiply near-zero.','Status templates (RIFLE_STATUS / PISTOL_STATUS / SHOTGUN_STATUS) for status-kind weapons below 15% base crit, excluding Incarnon families (form/evolutions change the crit profile). 19 slots switched, incl. audited Citrine/Follie/Frost secondaries (decisions unchanged).','Mod lists only. All mods are in the all-mods collection: no procurement change.'),
 ('v4.3 B3 SYSTEMIC: element order','Element results were hand-written labels; no check that Arcane element triggers were satisfied','Combination rules: mod elements combine in slot order; an innate element merges into the same mod element, else appends last; Melee Influence needs Electricity; Primary Frostbite needs Cold.','Automated element engine + validator on all 183 weapon slots and 19 Exalteds; labels now computed. Caught Frost Prime Glaxion Vandal: Primary Frostbite with a Viral-only result (Cold consumed). Fixed to pure Cold. Exalted labels "Viral+Heat" on melee Exalteds were wrong (mods only make Viral).','Display + one mod list. No procurement change.'),
 ('v4.3 B3 SYSTEMIC: no-energy frames','Engine banned Streamline/Fleeting Expertise on Hildryn and Lavos ("Efficiency irrelevant")','Hildryn passive: "Ability Efficiency mods affect the shield costs of her abilities". Lavos: Efficiency affects Transmutation Probe / Swift Bite cooldown reduction.','Rule narrowed to energy-pool mods (Flow / Primed Flow / Archon Flow). Hildryn takes Streamline.','None.'),
 ('v4.3 B3 SYSTEMIC: Augur set on no-energy frames','Augur Reach / Augur Accord treated as full Augur value on Hildryn and Lavos','Wiki (both passives): mods converting energy spent to shields, such as the Augur set, do not replenish shields.','Hildryn: Augur Reach -> Streamline (Accord kept for its shield-capacity stat). Lavos: Augur Reach -> Swift Bite.','None.'),
 ('v4.3 B4 SYSTEMIC: Helminth damage-buff restriction','Validator allowed Roar in any slot','Wiki Helminth "Damage buff restrictions": Eclipse/Roar/Xata\'s Whisper may ONLY replace Vex Armor (Chroma), Resupply (Cyte-09), Eclipse (Mirage), Amp (Octavia), Silken Stride (Oraxia), Roar (Rhino), Ripper\'s Wail (Temple), Demonium (Uriel), Xata\'s Whisper (Xaku).','Rule added to engine.py. All 66 scanned: only Oraxia violated (Roar over Mercy\'s Kiss -> NO HELMINTH). Xaku\'s Roar over Xata\'s Whisper is legal (forced slot).','None.'),
 ('v4.3 B4 SYSTEMIC: augment cross-dependency','Validator only checked that an augment\'s own target ability was not subsumed','Molecular Fission (Molecular Prime augment) only works on enemies hit by Null Star; Nova v4.2 had subsumed Null Star.','AUG_REQUIRES rule (Molecular Fission, Blazing Pillage, Temporal Artillery/Erosion, Wrecking Wall, Reinforcing Stomp, Ironclad Charge, Cathode Current, Wrath of Ukko, Aegis Gale). All 66 scanned: Nova was the only violation.','None.'),
 ('v4.3 B4 SYSTEMIC: weapon classification','Incarnon weapons classified on base-mode stats; <15% crit auto-selected a status build','Incarnon Form stats differ sharply (Boltor Prime 12% -> 24%/3x, Bronco Prime 6% -> 24%/3.2x, Dual Toxocyst 5% -> 11%/43% status); perks such as Devastating Attrition invert the crit rule.','Incarnon weapons now classified on their Incarnon Form; the <15% threshold only FLAGS a weapon. Every flagged slot on an audited frame carries an explicit review note (WEAPON CONFIGS columns). Arcane/element triggers are checked after combination.','Mod lists only; no procurement change.'),
 ('v4.3 B5 SYSTEMIC: Secondary Outburst default','Default weapon rule gave Secondary Outburst to melee-centric frames (Ash, Excalibur Umbra, Valkyr, Wukong, Garuda, Kullervo, Baruuk, Voruna)','Arcane data: Outburst CONSUMES all melee combo on swap; those frames build combo for Talons/Iron Staff/Exalted Blade/Desert Wind/heavy attacks.','All seven remaining users moved to Secondary Dexterity (melee kills -> secondary damage, +combo duration); Ash had been corrected in Batch 1.','Secondary Dexterity already required (Kullervo); Outburst drops to optional collection.'),
 ('v4.3 B5 SYSTEMIC: Exalted Warframe slots','v4.2: Sevagoth\'s Shadow "no shards/arcanes slots"; Orion Arcanes/shards/Reactor LIVE TEST','Wiki: the Shadow uses its own equipped Mods AND Arcanes (Shards/Focus apply normally). Sirius & Orion: separate Mods/Aura/Arcanes, SHARED Archon Shards, Orion has a pre-installed Reactor, Helminth on the Primary Son only, weapons/mods/Arcanes shared, identical Auras do not stack.','Shadow given Arcane Fury + Arcane Reaper; Orion given its own Arcanes and a different Aura (Corrosive Projection). Three S&O LIVE TESTs closed.','No new purchases (Arcane copies are reusable across configs like mods; Reactor pre-installed).'),
 ('v4.3 B5 SYSTEMIC: Incarnon perk vs crit template','Template chose crit mods regardless of the selected Incarnon perks','Laetum Devouring Attrition (+2000% on non-crit hits) and Elemental Excess (-10% crit); Furis Prelude of Might (+3x crit multiplier only below 40% crit).','Laetum -> status build; Furis -> no crit-chance mods. Same class as Felarx (B4).','None.'),
]
