# Signature weapons (live wiki "Signature Weapon" page, 2026-10-05): weapon -> (frame, bonus)
SIG = {
 'Tekko Prime':('Atlas Prime','+6% Status Chance'),
 'Euphona Prime':('Banshee Prime','Signature, bonus not implemented'),
 'Cobra & Crane Prime':('Baruuk Prime','First combo strike sleeps 2s (not allocated: Desert Wind replaces Melee)'),
 'Venato Prime':('Caliban Prime','+50% Melee Combo Counter Chance'),
 'Vadarya Prime':('Caliban Prime','Signature, bonus not implemented'),
 'Steflos Prime':('Citrine Prime','+40% Projectile Speed'),
 'Corufell Prime':('Citrine Prime','+20% Heavy Attack Wind Up Speed'),
 'Reconifex':('Cyte-09','Signature, bonus not implemented (not allocated: Neutralizer replaces Primary)'),
 'Dorrclave':('Dagath','Heals 6 HP per active status on strike'),
 'Ruvox':('Dante','Signature, bonus not implemented'),
 'Skiajati':('Excalibur Umbra','Signature, bonus not implemented (not allocated: Exalted Blade replaces Melee)'),
 'Enkaus':('Follie','Alt-fire applies Inkblot passive'),
 'Astilla Prime':('Gara Prime','+80 Ammo Max'),
 'Fusilai':('Gara Prime','+50% Projectile Speed'),
 'Volnus Prime':('Gara Prime','+100% radial Slam damage'),
 'Nagantaka Prime':('Garuda Prime','+1m Punch Through'),
 'Acceltra Prime':('Gauss Prime','Sprint reload buff +50%'),
 'Akarius Prime':('Gauss Prime','Sprint reload buff +100%'),
 'Masseter Prime':('Grendel Prime','CC immunity during Heavy Attacks'),
 'Alternox Prime':('Gyre Prime','+20% Multishot'),
 'Knell Prime':('Harrow Prime','+1 Magazine'),
 'Scourge Prime':('Harrow Prime','Signature, bonus not implemented'),
 'Larkspur Prime':('Hildryn Prime','+300 Ammo Max in atmosphere (ARCHGUN - not a Primary)'),
 'Evensong':('Jade','Signature, bonus not implemented'),
 'Cantare':('Jade','Signature, bonus not implemented'),
 'Harmony':('Jade','Signature, bonus not implemented'),
 'Hystrix Prime':('Khora Prime','8% instant reload on headshot'),
 'Dual Keres Prime':('Khora Prime','20% Heavy Attack Efficiency'),
 'Higasa':('Koumei','Signature, bonus not implemented'),
 'Amanata':('Koumei','Signature, bonus not implemented'),
 'Rauta':('Kullervo','+7s Melee Combo duration'),
 'Cedo Prime':('Lavos Prime','Shotgun Ammo Mutation effect'),
 'Akzani':('Mirage Prime','Signature, bonus not implemented (not allocated)'),
 'Nunchasa':('Narin','Signature, bonus not implemented'),
 'Aksondol':('Narin','Signature, bonus not implemented'),
 'Arbucep':('Nokko','Shooting Stinkbrain/Brightbonnet triggers pulses (ARCHGUN)'),
 'Pandero Prime':('Octavia Prime','Alt-fire headshot kills +20% reload'),
 'Tenora Prime':('Octavia Prime','Alt-fire headshot kills 20% mag refill'),
 'Scyotid':('Oraxia','Signature, bonus not implemented'),
 'Spinnerex':('Oraxia','Signature, bonus not implemented'),
 'Wrath':('Sirius & Orion','Signature (Orion), bonus not implemented (not allocated)'),
 'Pride':('Sirius & Orion','Signature (Sirius), bonus not implemented (not allocated)'),
 'Velox Prime':('Protea Prime','Ammo Efficiency 40%'),
 'Mandonel':('Qorvex','Charged beams empower Chyrinka Pillar (ARCHGUN)'),
 'Phantasma Prime':('Revenant Prime','+4 Magazine'),
 'Tatsu Prime':('Revenant Prime','+4 Soul Swarm charges'),
 'Epitaph Prime':('Sevagoth Prime','+20% headshot damage'),
 'Afentis Prime':('Styanax Prime','+4 flat Ammo Max'),
 'Riot-848':('Temple','Signature, bonus not implemented (not allocated)'),
 'Perigale Prime':('Voruna Prime','+24 Ammo Max'),
 'Sarofang Prime':('Voruna Prime','Heavy Slam vortex at 5x combo'),
 'Vinquibus':('Uriel','Signature, bonus not implemented; occupies Primary AND Melee'),
 'Fulmin Prime':('Wisp Prime','Faster auto/semi mode switch'),
 'Quassus Prime':('Xaku Prime','Heavy Attack daggers +Accuracy'),
 'Kompressa Prime':('Yareli Prime','+30% Projectile Speed'),
}
ELEMENT = {'Kuva Hek':'toxin','Tenet Plinx':'toxin','Tenet Diplos':'toxin','Tenet Detron':'radiation','Kuva Nukor':'heat',
 'Kuva Sobek':'toxin','Tenet Arca Plasmor':'radiation','Kuva Bramma':'heat','Tenet Cycron':'toxin','Kuva Ogris':'toxin',
 'Kuva Twin Stubbas':'heat','Tenet Spirex':'electricity'}
# Rationale for changed / newly assigned slots
CHANGES = {
 ('Baruuk Prime','Primary'):('OPEN','Paris Prime','Afentis is Styanax signature. Paris Prime Incarnon: high-end bow, unallocated, Genesis farmable. Tier D/E.'),
 ('Dante','Primary'):('Ruvox','Phenmor','Ruvox is a MELEE (Fist), not a Primary. Phenmor: Entrati/Albrecht innate Incarnon rifle, Whispers-era fit (D).'),
 ('Dante','Melee'):('Ekhein','Ruvox','Ruvox is Dante signature melee (A/B claim, innate Incarnon). Ekhein released to pool.'),
 ('Garuda Prime','Secondary'):('Zakti Prime','Despair','Zakti Prime duplicate (Garuda vs Nezha); neither has a signature claim. Nezha keeps it (Prime Access tie-break only). Despair Incarnon: thrown blades suit talon kit (D).'),
 ('Hildryn Prime','Primary'):('Larkspur Prime','Gorgon Wraith','Larkspur Prime is an ARCHGUN, so the Primary slot was effectively empty. Larkspur moved to an Archgun signature extra. Gorgon Wraith Incarnon (E).'),
 ('Koumei','Secondary'):('Kompressa','Kunai','Kompressa line is Yareli signature (+30% Projectile Speed); Kompressa Prime exists. Kunai Incarnon: Japanese-themed thrown sidearm (D).'),
 ('Narin','Melee'):('OPEN','Prisma Skana','Nurinarim is a cast sword-dance ability (scales on Ability Strength, 20s, no weapon mods), not a wielded weapon, so it does NOT replace Melee. Prisma Skana Incarnon: sword fits Iceblade theme (D).'),
 ('Nokko','Primary'):('OPEN','Sporothrix','Fungal sniper rifle, direct Nokko (mushroom) thematic fit (D). Signature Arbucep is an Archgun.'),
 ('Nokko','Secondary'):('OPEN','Ocucor','Released from Yareli; Deimos/Infested-growth thematic fit (D).'),
 ('Nokko','Melee'):('OPEN','Mios','Released from Uriel (Vinquibus covers Melee); Infested blade-whip fit (D).'),
 ('Oraxia','Primary'):('OPEN','Torid','Toxin launcher Incarnon; venom/spider fit (D).'),
 ('Qorvex','Secondary'):('Laetum','Bronco Prime','Laetum duplicate (Qorvex vs Xaku). Xaku keeps it (Void/Zariman fit). Bronco Prime Incarnon: hitscan sidearm exploits +3 Punch Through passive (C).'),
 ('Qorvex','Melee'):('Quassus','Hate','Quassus is XAKU signature; Qorvex had no claim. Hate Incarnon (E).'),
 ('Styanax Prime','Primary'):('Afentis','Afentis Prime','Afentis Prime is live; same signature bonus line.'),
 ('Uriel','Melee'):('Mios','Vinquibus (Melee)','Vinquibus occupies BOTH Primary and Melee slots, so Mios was impossible to equip alongside it.'),
 ('Wukong Prime','Secondary'):('Pyrana Prime','Ballistica Prime','Pyrana Prime duplicate (Limbo vs Wukong). Limbo keeps it (Prime Access tie-break only). Ballistica Prime Incarnon (E).'),
 ('Yareli Prime','Secondary'):('Ocucor','Kompressa Prime','Signature with a mechanical bonus (+30% Projectile Speed), tier A.'),
}
CORRECTIONS = [
 ('Roster','Roster may contain new frames/Primes','Live wiki data 2026-10-05: no new released frames or Primes since the 66-frame snapshot. Brysko is announced for the Tau update (Late 2026/Early 2027). Excalibur Umbra Prime is China-build only.','Roster unchanged at 66 frames. Brysko goes on a watchlist.','Frame counts unchanged.'),
 ('Uriel','Vinquibus Primary + Mios Melee','Vinquibus wiki: "Equipping Vinquibus will occupy both primary and melee weapon slots."','Uriel Melee = Vinquibus (Melee). Mios released.','One fewer weapon, slot and catalyst. Mios reassigned to Nokko.'),
 ('Dante','Ruvox as Primary','Weapon data: Ruvox is a Melee Fist and Dante\'s signature melee. Ekhein is also Melee.','Phenmor / Onos / Ruvox. Ekhein dropped.','Dante had no valid Primary and two Melees.'),
 ('Hildryn','Larkspur Prime as Primary','Weapon data: Larkspur Prime Slot = Archgun.','Gorgon Wraith takes Primary. Larkspur Prime becomes an Archgun signature extra (Archweapon slot).','Adds one Primary weapon and one Genesis adapter.'),
 ('Rhino','Ankyros Prime Incarnon','Incarnon page and weapon data: no Ankyros Incarnon exists.','Ankyros Prime kept as an ordinary weapon. Incarnon flag removed.','Removes one Genesis requirement.'),
 ('Vauban','Kulstar Incarnon','Incarnon page and weapon data: no Kulstar Incarnon exists.','Kulstar kept as an ordinary weapon. Incarnon flag removed.','Removes one Genesis requirement.'),
 ('Incarnon list','20-item historical Incarnon list','Allocated weapons with a live Incarnon now total 39: 32 need a Genesis adapter and 7 are innate (Innodem, Praedos, Ruvox, Phenmor, Onos, Felarx, Laetum). Sybaris Prime, Sicarus Prime and Okina Prime were already allocated but were not flagged.','Incarnon list rebuilt from live data.','Genesis adapters are farmable (Steel Path Circuit), not plat.'),
 ('Styanax','Afentis','Afentis Prime is live (Update 43) with the same signature bonus.','Afentis Prime.','Afentis Prime Set priced instead of base Afentis.'),
 ('Yareli / Koumei','Koumei holds Kompressa, Yareli uses Ocucor','Kompressa / Kompressa Prime are Yareli signatures (+30% Projectile Speed). Koumei has no claim.','Yareli: Kompressa Prime. Koumei: Kunai. Ocucor goes to Nokko.','Kompressa Prime Set priced.'),
 ('Qorvex','Felarx / Laetum / Quassus','Quassus is Xaku\'s signature line. Laetum collides with Xaku. Qorvex\'s only signature is the Mandonel archgun. The passive is +3 Punch Through for any weapon.','Felarx / Bronco Prime / Hate, plus Mandonel.','Removes two collisions.'),
 ('Narin','Nurinarim LIVE TEST','Ability page: a 20s sword-dance ability that drains Ice and scales on Ability Strength, with no weapon modding. Same doctrine class as the U38.5 cast-based conversions.','No replacement. Ordinary Melee required: Prisma Skana.','Adds one Melee.'),
 ('Dante','Noctua not addressed','Weapon data: Noctua is an Exalted secondary (first ability).','Treated like Jade\'s Glory: an additional Exalted that does not replace Onos.','LIVE TEST if a different ruling is wanted.'),
 ('Garuda','Garuda Talons as Exalted','Weapon data: Garuda Prime Talons is class Claws, used when no melee is equipped (passive). No slot or catalyst.','Kept as practical Melee. Excluded from slot and catalyst counts.','-'),
 ('Protea','Roar replaces Temporal Anchor while running Temporal Artillery','Mod data: Temporal Artillery is a Blaze Artillery augment that only triggers "When Temporal Anchor is activated".','INTERNALLY INVALID. Recommended: Roar over Grenade Fan, keeping Temporal Anchor + Temporal Artillery. Alternative: keep Roar on Anchor and drop Temporal Artillery.','Build sheet must be edited in the v3 workbook (not available here).'),
 ('Mesa','Regulators credited as Melee','Weapon data lists Regulators Prime as an Exalted Secondary.','Project doctrine kept (Melee credit). Game-side slot noted.','None.'),
 ('Duplicates','"Zero duplicates" after earlier cleanup','Logical audit of 66x3 slots found exact duplicates Zakti Prime, Pyrana Prime and Laetum, plus a hidden Quassus/Quassus Prime signature conflict.','All resolved (see Weapon Allocation). 0 exact duplicates.','Variant-family pairs remain by design: Vectis/Vectis Prime, Trumna/Trumna Prime, Dual Keres/Prime, Epitaph/Prime, Cedo/Prime, Pyrana/Pyrana Prime, Ohma/Prisma Ohma.'),
 ('Zephyr','Catchmoon','Catchmoon is a Kitgun chamber and not tradeable.','Kept. Classified as farmable (Solaris United).','No plat.'),
 ('Temple / Mirage / S&O','Signature weapons not used','Temple Riot-848, Mirage Akzani and Sirius/Orion Pride/Wrath are signatures, but their bonuses are "not implemented".','Allocation unchanged (no mechanical claim). Flagged for preference.','-'),
]
